name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

      
jobs:
    build:
        runs-on: debian-latest

        strategy:
            matrix:
                node-version: [20.x, 19.x]
        
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
                node-version: ${{ matrix.node-version }}
        - run: npm start